baseURL = 'https://shuttercoach.com/'
languageCode = 'en-us'
title = 'ShutterCoach – Weather-Based Camera Settings for Photographers'
theme = 'hugo-theme-shutter-coach-nextjs'
paginator = 2

[params]
  author = 'ShutterCoach'
  description = 'Get AI-powered camera settings recommendations based on current weather, scene type, and light conditions. Perfect for beginner photographers.'
  disqusShortname = 'shuttercoach'
  keywords = 'camera settings, weather photography, aperture priority, ISO calculator, shutter speed tips, photography tools, beginner photography, sunlight portrait setup, SEO for photographers'
