baseURL = 'https://shuttercoach.com/'
languageCode = 'en-us'
title = 'Golang Snippets – Practical Go code examples for everyday development'
theme = 'hugo-theme-go-snippets'
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
canonifyURLs = true
relativeURLs = false

[permalinks]
  posts = ":slug"

[outputs]
  home = ["HTML", "RSS", "JSON", "WebAppManifest"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  term = ["HTML", "RSS"]

[sitemap]
  changefreq = 'weekly'
  priority = 0.7
  filename = 'sitemap.xml'

[taxonomies]
  category = 'categories'
  tag = 'tags'
  series = 'series'

[minify]
  disableXML = true
  minifyOutput = true
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false

[imaging]
  resampleFilter = 'CatmullRom'
  quality = 85
  anchor = 'smart'
  bgColor = '#ffffff'
  hint = 'photo'

[security]
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
  [security.funcs]
    getenv = ['^HUGO_', '^CI$']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$'], ['\[', '\]']]
          inline = [['\(', '\)']]

  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = 'dracula'
    tabWidth = 2

[params]
  description = "Golang code examples, Go snippets for developers. Providing high-quality Golang language code snippets to help developers solve problems quickly and improve development efficiency."
  author = "Silas"
  defaultImage = "https://image.ypplog.cn/go-snippets-og-image.avif"

  [params.contact]
    email = "mazaoshe@hotmail.com"
    github = "https://github.com/mazaoshe"
    
  [params.categoryConfig]
    "DateTime" = { icon = "⏰", description = "Working with time, dates, and duration in Golang", displayName = "DateTime", order = 1 }
    "Strings" = { icon = "📝", description = "String manipulation and formatting in Golang", displayName = "Strings", order = 2 }
    "JSON" = { icon = "📋", description = "JSON parsing and serialization in Golang", displayName = "JSON", order = 3 }
    "Files" = { icon = "📁", description = "File operations and input/output in Golang", displayName = "Files", order = 4 }
    "HTTP" = { icon = "🌐", description = "HTTP clients and servers in Golang", displayName = "HTTP", order = 5 }
    "Concurrency" = { icon = "⚡", description = "Goroutines and channels in Golang", displayName = "Concurrency", order = 6 }
    "Cryptography" = { icon = "🔐", description = "Encryption and hashing in Golang", displayName = "Cryptography", order = 7 }
    "Testing" = { icon = "🧪", description = "Unit testing and benchmarks in Golang", displayName = "Testing", order = 8 }
    "Web" = { icon = "🌐", description = "Web development with Golang", displayName = "Web", order = 9 }
    
  [params.defaultCategoryConfig]
    icon = "📚"
    description = "Golang programming examples"
    displayName = "Other"
    order = 100

  [params.keywords]
    keywords = [
      "Golang snippets",
      "Golang examples", 
      "Golang code snippets",
      "Go code examples",
      "Practical Go code",
      "Go programming",
      "Go development",
      "Go tutorial"
    ]